#!/usr/bin/env python
"""
Plot a difference between two all_ions_and_molcules.hist files
generated by SDF.x
"""
import os, sys, commands, glob
import pylab, Numeric

def main():

    # Retrieve user input
    try:
        f = open(sys.argv[1],'r')
        header1 = f.readline()
        lines1 = f.readlines()
        f.close()
        f = open(sys.argv[2],'r')
        header2 = f.readline()
        lines2 = f.readlines()
        f.close()
    except:
        print '\n usage: '+sys.argv[0]+' all_ions_and_molecules.hist, all_ions_and_molecules.hist\n'
        sys.exit(0)

    # Check that the files align
    if len(lines1) != len(lines2):
        print '\nThe two given files do not align. exiting...\n'
        sysy.exit(0)

    # Initialize arrays and counting variables
    R, THETA, delta_SDF = [], [], []
    k = -1

    # Read in the data and format
    for i in range(len(lines1)):

        row1 = lines1[i].split()
        row2 = lines2[i].split()
        r = float(row1[0])
        theta = float(row1[1])
        delta_sdf = float(row1[2]) - float(row2[2])

        if r not in R:
            R.append(r)
            delta_SDF.append([])
            k += 1
        if theta not in THETA:
            THETA.append(theta)

        if delta_sdf == 0.0:
            delta_sdf = 1E-6

        delta_SDF[k].append(delta_sdf)

    THETA = Numeric.array(THETA)*180./Numeric.pi
    R = Numeric.array(R)*0.529177

#    print Numeric.shape(X),Numeric.shape(Y),Numeric.shape(Z)

    # Create the plot
    pylab.figure(num=1,figsize=(8,4),facecolor='w',edgecolor='k')
    pylab.contourf(THETA,R,delta_SDF,100,antialiased=False)
    pylab.title('delta_SDF',fontsize=14)
    pylab.xlabel('THETA',fontsize=12)
    pylab.ylabel('R',fontsize=12)
    pylab.colorbar()

    pylab.savefig('delta_SDF.png')
    pylab.clf()

#    pylab.show()


if __name__ == '__main__':
    main()
